import type { CatalogItem } from '../lib/broadcastClock'

// Generated by npm run bundle:programs. Only the selected channel's import is invoked.
export const CURATED_PROGRAMS: Partial<Record<string, {
  version: string
  load: () => Promise<CatalogItem[]>
}>> = {
  "Bollywood": {
    version: '438a3733be241676',
    load: () => import('./programs/001.json').then(m => m.default),
  },
  "Cricket": {
    version: '0e662c6f524a9279',
    load: () => import('./programs/002.json').then(m => m.default),
  },
  "Jungle Book": {
    version: '4fc3bf87e17336e9',
    load: () => import('./programs/003.json').then(m => m.default),
  },
  "Shaktimaan": {
    version: '1fa7e500277ef6bc',
    load: () => import('./programs/004.json').then(m => m.default),
  },
  "DD Classics": {
    version: '0a896f3950bb41e2',
    load: () => import('./programs/005.json').then(m => m.default),
  },
  "Ramayan": {
    version: '4abbb2236c2dcf4d',
    load: () => import('./programs/006.json').then(m => m.default),
  },
  "Mahabharat": {
    version: 'b69b996768801d67',
    load: () => import('./programs/007.json').then(m => m.default),
  },
  "Animals": {
    version: '6e82f21452ac8444',
    load: () => import('./programs/008.json').then(m => m.default),
  },
  "Street Food": {
    version: '470b76e643be55fe',
    load: () => import('./programs/009.json').then(m => m.default),
  },
  "Space": {
    version: '968b5bf2cab47abc',
    load: () => import('./programs/010.json').then(m => m.default),
  },
  "Football": {
    version: 'ea992d57aba8f745',
    load: () => import('./programs/011.json').then(m => m.default),
  },
  "Tokyo": {
    version: 'f4cbf4480610257e',
    load: () => import('./programs/012.json').then(m => m.default),
  },
  "Vintage India": {
    version: '44f196d03e657592',
    load: () => import('./programs/013.json').then(m => m.default),
  },
  "Dogs": {
    version: 'aba07c115e154495',
    load: () => import('./programs/014.json').then(m => m.default),
  },
  "Kitchen": {
    version: 'f47179765427e3d8',
    load: () => import('./programs/015.json').then(m => m.default),
  },
  "Formula": {
    version: '6ccd7a5908233e1b',
    load: () => import('./programs/016.json').then(m => m.default),
  },
  "Craft": {
    version: '2db5d7e9f7f765e0',
    load: () => import('./programs/017.json').then(m => m.default),
  },
  "Good News": {
    version: 'a67386bf30630806',
    load: () => import('./programs/018.json').then(m => m.default),
  },
  "Safari": {
    version: 'd627e689848266c7',
    load: () => import('./programs/019.json').then(m => m.default),
  },
  "Dance": {
    version: '02417af4d35b261a',
    load: () => import('./programs/020.json').then(m => m.default),
  },
  "Olympics": {
    version: '2d281284f468c117',
    load: () => import('./programs/021.json').then(m => m.default),
  },
  "Talks": {
    version: '9811f91fba63ea41',
    load: () => import('./programs/022.json').then(m => m.default),
  },
  "Cats": {
    version: 'deaaf89056720402',
    load: () => import('./programs/023.json').then(m => m.default),
  },
  "Circus": {
    version: '45ea661baeb125dc',
    load: () => import('./programs/024.json').then(m => m.default),
  },
  "Nature": {
    version: '9cef595641d571b4',
    load: () => import('./programs/025.json').then(m => m.default),
  },
  "Ocean": {
    version: 'a0177e550a9dfefe',
    load: () => import('./programs/026.json').then(m => m.default),
  },
  "Lofi": {
    version: '4f6cd7bda63cda17',
    load: () => import('./programs/027.json').then(m => m.default),
  },
  "Classic Music": {
    version: '43ea950f34781332',
    load: () => import('./programs/028.json').then(m => m.default),
  },
  "Rain": {
    version: 'c29b55f6040eca96',
    load: () => import('./programs/029.json').then(m => m.default),
  },
  "Fireplace": {
    version: 'fbc92336a681ce85',
    load: () => import('./programs/030.json').then(m => m.default),
  },
  "Forest": {
    version: '3d4f3dfa46f03c08',
    load: () => import('./programs/031.json').then(m => m.default),
  },
  "Mountains": {
    version: '603b490e64edac96',
    load: () => import('./programs/032.json').then(m => m.default),
  },
  "Desert": {
    version: '1a42d4cff3b34b01',
    load: () => import('./programs/033.json').then(m => m.default),
  },
  "River": {
    version: 'd21b90c0b85db09a',
    load: () => import('./programs/034.json').then(m => m.default),
  },
  "Falls": {
    version: '94c519941a2d9951',
    load: () => import('./programs/035.json').then(m => m.default),
  },
  "Snow": {
    version: '3484f269a18544f0',
    load: () => import('./programs/036.json').then(m => m.default),
  },
  "Aurora": {
    version: '92f58927d3e987bc',
    load: () => import('./programs/037.json').then(m => m.default),
  },
  "Clouds": {
    version: '9ce0ad2a5f84858f',
    load: () => import('./programs/038.json').then(m => m.default),
  },
  "Stars": {
    version: 'f8b24584156caa53',
    load: () => import('./programs/039.json').then(m => m.default),
  },
  "Aquarium": {
    version: '3c9473f384185535',
    load: () => import('./programs/040.json').then(m => m.default),
  },
  "Birds": {
    version: 'bf2ed0862d3a3dd8',
    load: () => import('./programs/041.json').then(m => m.default),
  },
  "Whales": {
    version: '22ba726e8dbfc6e1',
    load: () => import('./programs/042.json').then(m => m.default),
  },
  "Horses": {
    version: '594f6deded59c63b',
    load: () => import('./programs/043.json').then(m => m.default),
  },
  "Pandas": {
    version: '7c76eb866ce2feca',
    load: () => import('./programs/044.json').then(m => m.default),
  },
  "Bees": {
    version: '9256963d0c8a4ce1',
    load: () => import('./programs/045.json').then(m => m.default),
  },
  "Farm": {
    version: '08d38dea5fbd3d5d',
    load: () => import('./programs/046.json').then(m => m.default),
  },
  "Reef": {
    version: 'd2b36d9fef16637b',
    load: () => import('./programs/047.json').then(m => m.default),
  },
  "Piano": {
    version: 'beaf0801235821de',
    load: () => import('./programs/048.json').then(m => m.default),
  },
  "Guitar": {
    version: '69bd16a35a27dce7',
    load: () => import('./programs/049.json').then(m => m.default),
  },
  "Violin": {
    version: '8dc1bd8300cf3220',
    load: () => import('./programs/050.json').then(m => m.default),
  },
  "Choir": {
    version: '737d91dbdc0eb6f0',
    load: () => import('./programs/051.json').then(m => m.default),
  },
  "Ambient": {
    version: 'a1fd180afddf73d3',
    load: () => import('./programs/052.json').then(m => m.default),
  },
  "Soul": {
    version: 'cafbd7ad5f5092e2',
    load: () => import('./programs/053.json').then(m => m.default),
  },
  "Blues": {
    version: '5d71bf3b0bf92e80',
    load: () => import('./programs/054.json').then(m => m.default),
  },
  "Reggae": {
    version: 'f216c67a9679290d',
    load: () => import('./programs/055.json').then(m => m.default),
  },
  "Bossa": {
    version: 'a4df0f3e4009af1e',
    load: () => import('./programs/056.json').then(m => m.default),
  },
  "Flamenco": {
    version: '3fd0246b917a4a65',
    load: () => import('./programs/057.json').then(m => m.default),
  },
  "Gospel": {
    version: 'c7eb261767ef7a8c',
    load: () => import('./programs/058.json').then(m => m.default),
  },
  "Disco": {
    version: '91ef645984597e2e',
    load: () => import('./programs/059.json').then(m => m.default),
  },
  "Funk": {
    version: '1748f12484d6d853',
    load: () => import('./programs/060.json').then(m => m.default),
  },
  "Score": {
    version: 'b2f3e922cd524730',
    load: () => import('./programs/061.json').then(m => m.default),
  },
  "Celtic": {
    version: 'b8ed7fb03fd1c1aa',
    load: () => import('./programs/062.json').then(m => m.default),
  },
  "Sitar": {
    version: 'afbf50642b361466',
    load: () => import('./programs/063.json').then(m => m.default),
  },
  "Kora": {
    version: '7e01e8efd2cb813a',
    load: () => import('./programs/064.json').then(m => m.default),
  },
  "Fado": {
    version: '178c1f90af1442e8',
    load: () => import('./programs/065.json').then(m => m.default),
  },
  "Gagaku": {
    version: '4618571e06a1c322',
    load: () => import('./programs/066.json').then(m => m.default),
  },
  "Mariachi": {
    version: '8307f1caecc467c4',
    load: () => import('./programs/067.json').then(m => m.default),
  },
  "Highlife": {
    version: '040d92190dff86e4',
    load: () => import('./programs/068.json').then(m => m.default),
  },
  "Gamelan": {
    version: 'd86c2bed445d4405',
    load: () => import('./programs/069.json').then(m => m.default),
  },
  "Opera": {
    version: 'a08ea6dcf9975b77',
    load: () => import('./programs/070.json').then(m => m.default),
  },
  "Harp": {
    version: 'e595f0766c2e0ead',
    load: () => import('./programs/071.json').then(m => m.default),
  },
  "Flute": {
    version: '75e31fc2126131ac',
    load: () => import('./programs/072.json').then(m => m.default),
  },
  "Organ": {
    version: '452ade6ad3088fd5',
    load: () => import('./programs/073.json').then(m => m.default),
  },
  "Baking": {
    version: '0ef31a5f7922c9b4',
    load: () => import('./programs/074.json').then(m => m.default),
  },
  "Coffee": {
    version: 'a17daa8799a30aff',
    load: () => import('./programs/075.json').then(m => m.default),
  },
  "Tea": {
    version: 'efa35d8afcbe4c5b',
    load: () => import('./programs/076.json').then(m => m.default),
  },
  "Pasta": {
    version: '5d96ecf6d7641c7e',
    load: () => import('./programs/077.json').then(m => m.default),
  },
  "Clay": {
    version: '3dd579be1a566d93',
    load: () => import('./programs/078.json').then(m => m.default),
  },
  "Wood": {
    version: '28c9bc6023d32aa1',
    load: () => import('./programs/079.json').then(m => m.default),
  },
  "Glass": {
    version: 'a11db7e456ea259d',
    load: () => import('./programs/080.json').then(m => m.default),
  },
  "Ink": {
    version: '42328ce707f41801',
    load: () => import('./programs/081.json').then(m => m.default),
  },
  "Paint": {
    version: 'fd11714f98c7d7be',
    load: () => import('./programs/082.json').then(m => m.default),
  },
  "Yarn": {
    version: '71ba9fe4114ff1be',
    load: () => import('./programs/083.json').then(m => m.default),
  },
  "Paper": {
    version: '744def29dafeaeaa',
    load: () => import('./programs/084.json').then(m => m.default),
  },
  "Paris": {
    version: 'a3320a78ba83d3de',
    load: () => import('./programs/085.json').then(m => m.default),
  },
  "Venice": {
    version: 'fbe84cf2e7da16e9',
    load: () => import('./programs/086.json').then(m => m.default),
  },
  "Kyoto": {
    version: 'd682da274d2e1a47',
    load: () => import('./programs/087.json').then(m => m.default),
  },
  "Marrakech": {
    version: 'ec0f1d1ec1059469',
    load: () => import('./programs/088.json').then(m => m.default),
  },
  "Havana": {
    version: '11b142465d1d47b9',
    load: () => import('./programs/089.json').then(m => m.default),
  },
  "Seoul": {
    version: '7001bc39b996e52e',
    load: () => import('./programs/090.json').then(m => m.default),
  },
  "Cairo": {
    version: 'fce6887b79dee241',
    load: () => import('./programs/091.json').then(m => m.default),
  },
  "Andes": {
    version: '2bd16ca738e4b770',
    load: () => import('./programs/092.json').then(m => m.default),
  },
  "Iceland": {
    version: 'e7838343a42f3bfc',
    load: () => import('./programs/093.json').then(m => m.default),
  },
  "Kerala": {
    version: '88894fcd3c41ef5e',
    load: () => import('./programs/094.json').then(m => m.default),
  },
  "Lisbon": {
    version: '16f2eba245872ea4',
    load: () => import('./programs/095.json').then(m => m.default),
  },
  "Yoga": {
    version: 'efe6f462932a55a3',
    load: () => import('./programs/096.json').then(m => m.default),
  },
  "Still": {
    version: 'ba2825c5fb2505e7',
    load: () => import('./programs/097.json').then(m => m.default),
  },
  "Tai Chi": {
    version: 'c8e62c355caa043a',
    load: () => import('./programs/098.json').then(m => m.default),
  },
  "Museum": {
    version: 'e4f6077ffe315fcc',
    load: () => import('./programs/099.json').then(m => m.default),
  },
  "Buildings": {
    version: '3a96bf75a1ff32ea',
    load: () => import('./programs/100.json').then(m => m.default),
  },
  "History": {
    version: '09471a88c9c06153',
    load: () => import('./programs/101.json').then(m => m.default),
  },
  "Rocks": {
    version: '2606c043f76212e1',
    load: () => import('./programs/102.json').then(m => m.default),
  },
  "Words": {
    version: '62d4b84523e6b8ac',
    load: () => import('./programs/103.json').then(m => m.default),
  },
  "Chess": {
    version: '321509b43e63857c',
    load: () => import('./programs/104.json').then(m => m.default),
  },
  "Gardens": {
    version: '9be02521f4b27f79',
    load: () => import('./programs/105.json').then(m => m.default),
  },
  "Trains": {
    version: 'f2100eda13b28606',
    load: () => import('./programs/106.json').then(m => m.default),
  },
  "Sailing": {
    version: 'f374d839a4a2a3bf',
    load: () => import('./programs/107.json').then(m => m.default),
  },
  "Tennis": {
    version: 'a00369edf6a39a7b',
    load: () => import('./programs/108.json').then(m => m.default),
  },
  "Hoops": {
    version: 'f2281e2c9b695238',
    load: () => import('./programs/109.json').then(m => m.default),
  },
  "Peloton": {
    version: '0a5887f2e330fa9f',
    load: () => import('./programs/110.json').then(m => m.default),
  },
  "Ice": {
    version: '8faf88772e10fde3',
    load: () => import('./programs/111.json').then(m => m.default),
  },
  "Surf": {
    version: '5434a51464ed8458',
    load: () => import('./programs/112.json').then(m => m.default),
  },
  "Trail": {
    version: '52234bae5b485993',
    load: () => import('./programs/113.json').then(m => m.default),
  },
  "Camp": {
    version: '0af37f383b7b98cb',
    load: () => import('./programs/114.json').then(m => m.default),
  },
  "Library": {
    version: '3709ddb82c60e000',
    load: () => import('./programs/115.json').then(m => m.default),
  },
  "Bookshop": {
    version: '04518bf311df9f01',
    load: () => import('./programs/116.json').then(m => m.default),
  },
  "Vinyl": {
    version: '6e6e2dd1ed3913da',
    load: () => import('./programs/117.json').then(m => m.default),
  },
  "Dawn": {
    version: 'a2c14735257742a6',
    load: () => import('./programs/118.json').then(m => m.default),
  },
  "Dusk": {
    version: 'c78980adc970d548',
    load: () => import('./programs/119.json').then(m => m.default),
  },
  "Storm": {
    version: '63df95ad447c8985',
    load: () => import('./programs/120.json').then(m => m.default),
  },
  "Wind": {
    version: '91b2add3c596e02a',
    load: () => import('./programs/121.json').then(m => m.default),
  },
  "Market": {
    version: 'b5eaa8dc4486cd44',
    load: () => import('./programs/122.json').then(m => m.default),
  },
  "Festival": {
    version: '373ca060485f2d30',
    load: () => import('./programs/123.json').then(m => m.default),
  },
  "Puppets": {
    version: 'd0297655ca72ae09',
    load: () => import('./programs/124.json').then(m => m.default),
  },
  "Lakes": {
    version: 'c5afa626638d4328',
    load: () => import('./programs/125.json').then(m => m.default),
  },
}
